version: '3.8'

services:
  pappobot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_USDA_API_KEY=${VITE_USDA_API_KEY}
    container_name: pappobot-app
    restart: unless-stopped
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    ports:
      - "3080:3000"
    volumes:
      # Mount entire project directory - reuse everything from non-Docker version
      - .:/app
    environment:
      # Environment variables can be overridden here
      - NODE_ENV=production
      # Pass the USDA API key to the container
      - VITE_USDA_API_KEY=${VITE_USDA_API_KEY}
    networks:
      - pappobot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=false"
      - "app.name=pappobot"
      - "app.version=1.0.0"
      - "app.description=PappoBot React Application"

  # Optional: Add a simple file browser for data management
  filebrowser:
    image: filebrowser/filebrowser:v2
    container_name: pappobot-filebrowser
    restart: unless-stopped
    ports:
      - "3081:80"
    volumes:
      - .:/srv/data
      - pappobot-filebrowser-config:/config
    environment:
      - FB_BASEURL=/files
    networks:
      - pappobot-network
    profiles:
      - management
    labels:
      - "app.name=pappobot-filebrowser"
      - "app.description=File browser for PappoBot data management"

volumes:
  # File browser configuration
  pappobot-filebrowser-config:
    driver: local

networks:
  pappobot-network:
    driver: bridge
    name: pappobot-network